name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          start: npm install #dependencies
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          env:  CYPRESS_spotify-password=${{ secrets.SPOTIFY_PASSWORD }},
                CYPRESS_spotify-username=${{ secrets.SPOTIFY_USERNAME }}
          start: node app.js
