name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          start: npm install #dependencies
          working-directory: ./web-api-auth-examples-master/authorization_code
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
      - run: nohup node app.js
      - run: wait 30s
      - run: npx cypress run
